-- MySQL Script generated by MySQL Workbench
-- 05/05/18 15:53:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `community`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `community` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `slug` VARCHAR(32) NULL,
  `description` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `date_inserted` DATETIME NULL,
  `date_updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `date_inserted` DATETIME NULL,
  `date_updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NULL,
  `presentation` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(60) NULL,
  `picture` VARCHAR(255) NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `date_inserted` DATETIME NULL,
  `date_updated` DATETIME NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NULL,
  `description` TEXT NULL,
  `price` DECIMAL(5,2) UNSIGNED NULL,
  `date_event` DATETIME NULL,
  `address` TEXT NULL,
  `zipcode` VARCHAR(20) NULL,
  `city` VARCHAR(64) NULL,
  `nb_guests` TINYINT UNSIGNED NULL,
  `is_virtual` TINYINT UNSIGNED NULL,
  `virtual_address` VARCHAR(255) NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `date_inserted` DATETIME NULL,
  `date_updated` DATETIME NULL,
  `community_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_community1_idx` (`community_id` ASC),
  INDEX `fk_event_user1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `community_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `community_has_user` (
  `community_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`community_id`, `user_id`),
  INDEX `fk_community_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_community_has_user_community_idx` (`community_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_has_user` (
  `event_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`event_id`, `user_id`),
  INDEX `fk_event_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_event_has_user_event1_idx` (`event_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
